"""nullable_product_id

Revision ID: 6b791c55304c
Revises: db4b9acbc494
Create Date: 2024-04-17 22:32:29.393779

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6b791c55304c"
down_revision: Union[str, None] = "db4b9acbc494"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sold_product",
        "product_id",
        existing_type=sa.BIGINT(),
        nullable=True,
    )
    op.drop_constraint(
        "fk_sold_product_product_id_product",
        "sold_product",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_sold_product_product_id_product"),
        "sold_product",
        "product",
        ["product_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_sold_product_product_id_product"),
        "sold_product",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_sold_product_product_id_product",
        "sold_product",
        "product",
        ["product_id"],
        ["id"],
    )
    op.alter_column(
        "sold_product",
        "product_id",
        existing_type=sa.BIGINT(),
        nullable=False,
    )
    # ### end Alembic commands ###
